### PR TITLE
fix url login for pocketbase 0.8.0-rc2 servers

### PR DESCRIPTION
**Pull request by o2dependent**

### CODE REVIEW

**Comment by o2dependent** [comment]
The reverts are from my formatter overwriting all git commits in schema.ts, so I reverted and added back the fix for 0.8.0-rc2 admin login. Commits can be squashed if needed before merging.

**Comment by patmood** [comment]
Good catch! Thanks for adding this. This is the first code contribution and the repo was not setup well for formatting.

I have just added eslint and prettier to the `rc` branch - Can you rebase and try again? You should be able to run `npm run format` to get everything formatted consistently.

**Comment by o2dependent** [comment]
I pulled in your formatting changes and squashed them so the commits aren't messy.

I really like this project so I'm also looking into ways to get full coverage with the URL testing! It would require locked-down creds for GitHub actions to run it but would be a great addition for future versions.

**Comment by patmood** [comment]
Looks good! For integration testing, I'm working on a docker image to launch a PB server, run the package against DB and URL, and compare it to a snapshot. Is that what you had in mind?

**Comment by o2dependent** [comment]
Yeah, that's what I was thinking as well! Then upload the collections JSON for use in the url tests. If you are planning on versioning this project with PocketBase and only supporting the most recent version it shouldn't be too crazy. Just bumping up the env var to pull the right version.

I've only worked with CI/CD in GitLab and AWS CodeCommit before so I might be a bit off base with how GitHub actions are handled though.

**Comment by patmood** [comment]
I'm also still figuring out github actions but I've started working on the test here https://github.com/patmood/pocketbase-typegen/pull/18

**Pull request merged**
